apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
bases:
- ../base
namespace: nginx-dev
images:
- name: nginx
  newName: altreze/dev-insurer-front
  newTag: "0.0.1"
patchesJson6902:
- path: patch-front.yaml
  target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: nginx-ing
