apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
bases:
- ../base
namespace: nginx-dev
images:
- name: nginx
  newName: altreze/insurer-api
  newTag: "0.0.3"
patchesJson6902:
- path: patch.yaml
  target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: nginx-ing
